spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://134.175.150.20:3306/t_mail?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useSSL=false
    username: root
    password: root
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: test

mybatis:
  mapperLocations: classpath:mapper/*.xml
  config-location: classpath:mybatis.xml
  type-aliases-package: com.easymail.easymail.entity

info:
  host: imap.163.com
  username: liuxiaochi721
  password: dianjigs12


filepath: C:/Users/xuwei/Desktop/tmp